# .goreleaser.yaml
project_name: seyir
dist: dist
env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: seyir
    main: ./cmd/seyir/main.go
    binary: seyir
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - id: seyir-archive
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - scripts/install.sh
    replacements:
      darwin: macOS
      linux: Linux
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: semihy
    name: seyir
  draft: false
  prerelease: auto
