# .goreleaser.yaml
version: 2

project_name: seyir

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: seyir
    main: ./cmd/seyir/main.go
    binary: seyir
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - id: seyir-archive
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - scripts/install.sh
      - src: "README.md"
        dst: "."
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: SemihY
    name: seyir
  draft: false
  prerelease: auto
