name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform Docker images
        run: |
          # Extract version parts for tagging
          VERSION=${{ github.ref_name }}
          TAGS="ghcr.io/semihy/seyir:latest,ghcr.io/semihy/seyir:$VERSION"
          
          if [[ $VERSION =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            TAGS="$TAGS,ghcr.io/semihy/seyir:v$MAJOR,ghcr.io/semihy/seyir:v$MAJOR.$MINOR"
          fi
          
          # Prepare tag args (robust handling)
          TAG_ARGS=()
          IFS=',' read -r -a arr <<< "$TAGS"
          for t in "${arr[@]}"; do
            TAG_ARGS+=(--tag "$t")
          done

          # Build and push multi-platform images
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            "${TAG_ARGS[@]}" \
            --build-arg VERSION="$VERSION" \
            --build-arg COMMIT=${{ github.sha }} \
            --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
            --push \
            .
