name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image manually
        run: |
          # Build the Linux binary for Docker
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X seyir/internal/version.Version=${{ github.ref_name }} -X seyir/internal/version.Commit=${{ github.sha }} -X seyir/internal/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o seyir ./cmd/seyir/main.go
          
          # Build and push Docker images
          docker build -t ghcr.io/semihy/seyir:latest .
          docker tag ghcr.io/semihy/seyir:latest ghcr.io/semihy/seyir:${{ github.ref_name }}
          
          # Extract version parts for additional tags
          VERSION=${{ github.ref_name }}
          if [[ $VERSION =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            docker tag ghcr.io/semihy/seyir:latest ghcr.io/semihy/seyir:v$MAJOR
            docker tag ghcr.io/semihy/seyir:latest ghcr.io/semihy/seyir:v$MAJOR.$MINOR
            docker push ghcr.io/semihy/seyir:v$MAJOR
            docker push ghcr.io/semihy/seyir:v$MAJOR.$MINOR
          fi
          
          docker push ghcr.io/semihy/seyir:latest
          docker push ghcr.io/semihy/seyir:${{ github.ref_name }}
